# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ddbe2337b7394973b50e37ffc320e928ffe0638a7cfaacf3f3dc0906035a9e475c92e00160f8ff1c4d709313309910ffb80c5162364a5080c2d0c99946fa0cda

test:
  secret_key_base: 08a0eb1b8f28ad3296eed31a9f6ba87333fdd09861f716ef4fb66deed21d334663dc815dc810fbb128bb77c619916ba35ec306ae9c0b7391d42e25b24f2ac3eb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
